spring.application.name=TickTrade

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:jfs}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true

# Error messages
spring.web.error.include-message=always

# Port
server.port=${PORT:8083}